#!/usr/bin/env node
/**
 * Orchestrator write path into the team event log.
 *
 *   echo '{"event":"agent.finish","slice":"03","actor":"implementer",...}' \
 *     | node tools/team-log/append.mjs
 *
 *   node tools/team-log/append.mjs --json '{"event":"slice.ready","slice":"00"}'
 *
 * Records written here are `reported` or `narrated`. **`derived` is refused** —
 * that tier asserts a fact came from tooling, and is reserved for the collectors
 * that compute it (collect-git.mjs, and the SubagentStop hook). See write.mjs.
 *
 * Exits non-zero on a schema violation and writes nothing.
 */
import { readFileSync } from 'node:fs';
import { appendRecords } from './write.mjs';

const argv = process.argv.slice(2);
const jsonFlag = argv.indexOf('--json');
const raw = jsonFlag !== -1
  ? argv[jsonFlag + 1]
  : (() => { try { return readFileSync(0, 'utf8'); } catch { return ''; } })();

if (!raw || !raw.trim()) {
  console.error("append: no event given. Pipe JSON on stdin or pass --json '{...}'.");
  process.exit(2);
}

let parsed;
try {
  parsed = JSON.parse(raw);
} catch (err) {
  console.error(`append: input is not valid JSON — ${err.message}`);
  process.exit(2);
}

let appended = 0;
try {
  for (const e of appendRecords(parsed)) {
    appended++;
    console.log(`logged ${e.event} · ${e.slice ? `slice ${e.slice}` : `phase ${e.phase}`} · ${e.span_id ?? ''}`);
  }
} catch (err) {
  console.error(`append: ${err.message}`);
  console.error('nothing was written.');
  process.exit(1);
}

/**
 * REGENERATE WHAT THIS APPEND JUST INVALIDATED — O-61, on its second occurrence.
 *
 * `docs/DEFECTS.md` and `docs/STATUS.md` are DERIVED from this log, so every append makes
 * them stale and `defects:check` red until someone remembers `npm run defects`. O-61 named
 * that the first time and was recorded rather than fixed; it then broke a running agent's
 * `test:tools` TWICE IN ONE SESSION, each time on work that had nothing to do with the
 * append, and each time the agent had to diagnose an orchestrator artifact to clear itself.
 *
 * O-61's own words were that a derived file regenerated by hand IS STALE BY DEFAULT, and
 * that the project keeps rediscovering that DERIVED ARTIFACTS NEED A TRIGGER, NOT A HABIT.
 * The append is the trigger: it is the only event that can invalidate them, and it is the
 * moment the writer is present. The same lesson as O-40's STATUS.md regression and the
 * `slice:check` mutation criterion — a guard whose only enforcement is discipline is not a
 * guard.
 *
 * It is BEST-EFFORT and never fails the append. A write that succeeded must not be reported
 * as failed because a derived view could not be rebuilt, and the log is the source of truth
 * either way: `defects:check` still catches the staleness if this does not run. `--no-regen`
 * exists for callers appending in a loop, where regenerating once at the end is the same
 * result for a fraction of the work.
 */
if (appended && !argv.includes('--no-regen')) {
  const { spawnSync } = await import('node:child_process');
  for (const tool of ['tools/defects/generate.mjs', 'tools/status/generate.mjs']) {
    const r = spawnSync(process.execPath, [tool], { stdio: 'ignore' });
    if (r.status !== 0) console.error(`append: note — ${tool} did not regenerate; run it before committing.`);
  }
}
