#!/usr/bin/env node
/**
 * Generate docs/STATUS.md — where the project is, and what happens next.
 *
 *   npm run status
 *
 * This exists because docs/board.html is gitignored and slice-scoped: nothing
 * about progress survived into a new session or onto another machine, and phase
 * work never appeared on the board at all. A session that begins by reading this
 * file knows where to resume without reconstructing it from the log by hand.
 *
 * Everything here is derived — from the event log, the ADR files, the slice
 * files and git. Nothing is narrated, so it cannot flatter.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { frontmatter } from '../lib/frontmatter.mjs';
import { loadLog } from '../team-log/write.mjs';

const OUT = resolve('docs/STATUS.md');

/** phase -> [title, the gate that closes it, what comes next] */
const PHASES = {
  '0': ['Foundation', null, '1'],
  '1': ['Requirements', 'A', '2'],
  '2': ['Architecture', 'B', '3'],
  '3': ['Backlog', 'C', '4'],
  '4': ['Pilot + retro', 'D', '5'],
  '5': ['Slice loop', 'E (per slice)', '6'],
  '6': ['Consolidation', 'F', '7'],
  '7': ['Video', null, null],
};

/**
 * Gate E fires on EVERY slice, so it closes nothing. Treating it as
 * phase-closing made the first slice gate of phase 5 report "phase 6,
 * consolidation" — with twelve slices still to build, in the one file that
 * exists to tell a resuming session where it is. Found at slice 00a's gate
 * (finding O-8); recorded rather than only fixed, because the generator agreed
 * with itself right up until a gate was actually decided.
 */
const PER_SLICE_GATES = new Set(['E']);

const events = loadLog().sort((a, b) => Date.parse(a.ts) - Date.parse(b.ts));

const gates = events.filter((e) => e.event === 'gate.decided');
const runs = events.filter((e) => e.event === 'agent.finish');
const dcrsOpen = events.filter((e) => e.event === 'dcr.raised').length
  - events.filter((e) => e.event === 'dcr.resolved').length;

// Position: the phase after the last gate decided, else the last phase touched.
const lastGate = [...gates].reverse().find((e) => !PER_SLICE_GATES.has(e.gate));
const lastPhaseTouched = [...events].reverse().find((e) => e.phase)?.phase;
const completedPhase = lastGate
  ? Object.keys(PHASES).find((p) => PHASES[p][1]?.startsWith(lastGate.gate))
  : null;
const current = completedPhase ? PHASES[completedPhase][2] : (lastPhaseTouched ?? '0');

const adrs = existsSync(resolve('docs/adr'))
  ? readdirSync(resolve('docs/adr'))
      .filter((f) => f.endsWith('.md') && !f.startsWith('_'))
      .map((f) => ({ file: f, ...frontmatter(readFileSync(join(resolve('docs/adr'), f), 'utf8')) }))
      .filter((a) => a.id)
      .sort((a, b) => String(a.id).localeCompare(String(b.id)))
  : [];

const slices = existsSync(resolve('docs/slices'))
  ? readdirSync(resolve('docs/slices'))
      .filter((f) => f.endsWith('.md') && !f.startsWith('_'))
      .map((f) => ({ file: f, ...frontmatter(readFileSync(join(resolve('docs/slices'), f), 'utf8')) }))
      .filter((s) => s.id && s.id !== '99')   // 99 is the board fixture, not work
  : [];

const fmt = (ms) => {
  if (!ms) return '—';
  const s = Math.round(ms / 1000);
  return s < 60 ? `${s}s` : `${Math.floor(s / 60)}m${String(s % 60).padStart(2, '0')}`;
};
const num = (n) => (n ?? 0).toLocaleString();

const tok = runs.reduce((a, r) => ({
  in: a.in + (r.tokens?.in ?? 0),
  out: a.out + (r.tokens?.out ?? 0),
  cr: a.cr + (r.tokens?.cache_read ?? 0),
  cw: a.cw + (r.tokens?.cache_write ?? 0),
}), { in: 0, out: 0, cr: 0, cw: 0 });

let head = '(unknown)';
try {
  head = execFileSync('git', ['log', '-1', '--format=%h %s'], { encoding: 'utf8' }).trim();
} catch { /* not a git repo */ }

const [curTitle, curGate] = PHASES[current] ?? ['Unknown', null];

const doc = `# Status

**Generated by \`npm run status\` — do not hand-edit.** Everything below is derived from
\`docs/team-log/events.jsonl\`, the ADR and slice files, and git. Nothing is narrated.

> **Resuming?** Read this, then [\`METHODOLOGY.md\`](METHODOLOGY.md) for the rules and
> [\`../CLAUDE.md\`](../CLAUDE.md) for the operative constraints. Run \`npm run log:audit\` before
> trusting any figure here.

---

## Where we are

**Phase ${current} — ${curTitle}**${curGate ? `, which closes at Gate ${curGate}` : ''}.

| | |
|---|---|
| Last commit | \`${head}\` |
| Gates decided | ${gates.length ? gates.map((g) => g.gate).join(', ') : 'none'} |
| Agent runs recorded | ${runs.length} |
| ADRs accepted | ${adrs.filter((a) => a.status === 'accepted').length} |
| Slices defined | ${slices.length} |
| Open DCRs | ${dcrsOpen > 0 ? `**${dcrsOpen}** — a slice is blocked` : 'none'} |

## What happens next

${nextActions(current, events, slices)}

## Gate decisions

${gates.length
  ? gates.map((g) => `**Gate ${g.gate}** · ${g.ts.slice(0, 10)} · ${g.decision}\n\n> ${g.rationale}`).join('\n\n')
  : '_No gates decided yet._'}

## Decisions on record

${adrs.length
  ? ['| ADR | Title | Status | AI input |', '|---|---|---|---|',
     ...adrs.map((a) => {
       const prov = (a['ai-input'] ?? '').match(/^\s*(OVERRIDDEN|MODIFIED|ACCEPTED|REJECTED)/i)?.[1] ?? '—';
       return `| [${a.id}](adr/${a.file}) | ${a.title ?? ''} | ${a.status} | ${prov.toLowerCase()} |`;
     })].join('\n')
  : '_None yet._'}

## Agent runs

${runs.length
  ? ['| When | Role | Duration | Tokens (in / out / cache-read) | Source |', '|---|---|---|---|---|',
     ...runs.map((r) => `| ${r.ts.slice(0, 16).replace('T', ' ')} | ${r.actor} | ${fmt(r.duration_ms)} | ${num(r.tokens?.in)} / ${num(r.tokens?.out)} / ${num(r.tokens?.cache_read)} | \`${r.source}\` |`),
     `| | **total** | **${fmt(runs.reduce((a, r) => a + (r.duration_ms ?? 0), 0))}** | **${num(tok.in)} / ${num(tok.out)} / ${num(tok.cr)}** | |`].join('\n')
  : '_No agent runs recorded._'}

Cache-read dominates fresh input by orders of magnitude, which is why the collector keeps the
breakdown rather than summing it. Figures are reconstructed from session transcripts and are not a
billing record.

---

*Board: \`npm run board\` (local, gitignored). Full log: \`npm run log\`.
Verify this file's figures against ground truth: \`npm run log:audit\`.*
`;

/**
 * The next action is a function of the phase AND of what has happened inside it.
 *
 * A static string per phase told a resuming session to "run slice 00 end-to-end,
 * then hold the retro" after both had been done and merged — the same class of
 * defect as O-8, in the same file: the resume point confidently naming work that
 * is finished. STATUS.md's own header tells the reader to trust it over
 * narration, so it has to be right about the inside of a phase, not only about
 * which phase it is.
 *
 * Phases 4 and 5 branch. The others become derived the first time one of them is
 * wrong about itself — which is how phase 5 got here: the moment Gate D closed
 * phase 4, this file's advice became "work slices one at a time, WIP 1", naming
 * no slice, on the one page a resuming session is told to trust. That is O-11's
 * shape exactly, one phase later, and it was static for the same reason.
 */
function nextActions(phase, events = [], slices = []) {
  const done = (id) => events.some((e) => e.event === 'slice.done' && String(e.slice) === id);
  const retroHeld = events.some(
    (e) => e.event === 'handoff' && String(e.artifact ?? '').includes('phase-4-retro'),
  );

  if (phase === '4') {
    if (!done('00a')) {
      return '- Run slice 00a (the walking skeleton) end-to-end.\n- Then slice 00, then the retro.\n- **Gate D**: tune the machine, or proceed.';
    }
    if (!done('00')) {
      return '- Slice 00a is done. Run slice 00 (the pilot) end-to-end.\n- Then hold the retro against `team-log/process-criteria.md`.\n- **Gate D**: tune the machine, or proceed.';
    }
    if (!retroHeld) {
      return '- Slices 00a and 00 are done. Hold the retro against `team-log/process-criteria.md`.\n- **Gate D**: tune the machine, or proceed.';
    }
    return [
      '- **Both pilot slices are done and the retro is written** — see [`team-log/phase-4-retro.md`](team-log/phase-4-retro.md).',
      '- Verdict: C1 PASS · C2 PASS on git, weakened on hooks · C3 PASS · C4 PASS · **C5 FAIL** · **C6 FAIL** · C7 PASS with three open defects · C8 the human\'s.',
      '- Two non-fatal criteria fail and neither is C1 nor C2, so the pre-registered decision rule reads: **tune the mechanisms and proceed to slice 01, no second pilot.**',
      '- **Gate D is open and undecided.** C6 is the one needing a ruling — its own wording says the response to a breach is to cut slices or reduce agent count, not to proceed and hope.',
      '- Open findings are in [`DEFECTS.md`](DEFECTS.md); the C2 and C7 clusters are what the retro says to tune first.',
    ].join('\n');
  }

  // Phase 5 — the slice loop. Derived from the backlog and the log together:
  // which slices are done, which has been started, and which one's dependencies
  // are satisfied. A static string here cannot know any of that, and the WIP
  // limit of 1 means naming the wrong slice is not a cosmetic error.
  if (phase === '5') {
    const backlog = [...slices].sort((a, b) => String(a.id).localeCompare(String(b.id)));
    const started = (s) => events.some((e) => String(e.slice) === String(s.id));
    const open = backlog.filter((s) => !done(String(s.id)));
    const inFlight = open.filter(started);
    const nextUp = open.find((s) => (s.depends_on ?? []).every((d) => done(String(d))));
    const folded = backlog.flatMap((s) => s.absorbs ?? []);
    const link = (s) => `[\`${s.id}\`](slices/${s.file})`;

    if (!open.length) {
      return '- **Every slice is done.** Phase 6: as-built arc42, README and §13.\n- **Gate F**: final read.';
    }
    const lines = [];
    if (inFlight.length) {
      lines.push(`- **Slice ${inFlight.map(link).join(', ')} is in flight** — ${inFlight[0].title}.`);
      lines.push('- **WIP limit is 1** (`CLAUDE.md` §8): nothing else starts until its **Gate E**.');
    } else if (nextUp) {
      lines.push(`- **Next: slice ${link(nextUp)} — ${nextUp.title}**`);
      lines.push(`- Nothing is in flight. Start at **step 1 of the slice loop**: the architect states building blocks, interfaces, the data-model delta and the applicable §10 scenarios.`);
      if (nextUp.quality_scenarios?.length) {
        lines.push(`- It claims ${nextUp.quality_scenarios.join(', ')}.`);
      }
    } else {
      lines.push(`- **No slice is startable** — ${open.length} open, none with its dependencies merged. That is a backlog defect, not a waiting state.`);
    }
    lines.push(`- ${open.length} slice(s) remain of ${backlog.length} defined${folded.length ? `; Gate D folded ${folded.length} (${folded.join(', ')}) into their successors` : ''}.`);
    lines.push('- **Gate E** on each, then `npm run slice:close`.');
    return lines.join('\n');
  }

  const map = {
    '0': '- Finish phase 0 instrumentation, then start phase 1.',
    '1': '- The architect writes arc42 §1–§3 and surfaces assumptions and open questions.\n- **Gate A**: the human resolves the open questions; answers become ADRs.',
    '2': [
      '- Branch `phase/02-architecture`, set the scope marker to `{"phase":"2"}`.',
      '- The architect writes arc42 §4–§8, §10 and §11, the founding `.dependency-cruiser.js`, and the presentation diagrams.',
      '- §10 must pin three obligations inherited from Gate A: the atomic-`UPDATE` reschedule (ADR-0003), no-spurious-refusal under retry (ADR-0004), and a move onto an interval overlapping the appointment\'s own current interval must succeed.',
      '- **Gate B**: plan-mode approval; the stack is confirmed here.',
    ].join('\n'),
    '3': '- Slice the backlog into ~14 files (rescheduling added one at Gate A).\n- **Gate C**: approve scope and ordering.',
    '6': '- As-built arc42 pass, presentation diagrams refreshed, README and §13 written.\n- **Gate F**: final read.',
    '7': '- Record the video from `docs/video-shotlist.md`.',
  };
  return map[phase] ?? '_Unknown phase._';
}

writeFileSync(OUT, doc, 'utf8');
console.log(`docs/STATUS.md ← phase ${current}, ${gates.length} gate(s), ${runs.length} run(s), ${adrs.length} ADR(s)`);
