#!/usr/bin/env node
/**
 * docs/DEFECTS.md — the defect register, generated from the event log.
 *
 * Ruled at slice 00a: findings live in `docs/team-log/events.jsonl` and the
 * register is derived, on the same reasoning as STATUS.md. Hand-maintaining it
 * would put it in the *written* tier, and this project has now caught six
 * mechanisms that looked fine because their failure was silent — a register
 * nobody updates would be the seventh.
 *
 * Scope, as ruled: anything crossing a role boundary, including a role's finding
 * against its own earlier work (S-1, A-1). A role's in-flight self-correction is
 * not a defect — recording those would make a careful role look worse than a
 * careless one.
 *
 * Rejected findings are kept WITH their ruling. A finding argued down on
 * reasoning is evidence the adjudication worked; slice 00a's sharpest case was a
 * correct finding whose proposed remedy would have broken the following slice.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const LOG = resolve('docs/team-log/events.jsonl');
const OUT = resolve('docs/DEFECTS.md');
const check = process.argv.includes('--check');

const events = existsSync(LOG)
  ? readFileSync(LOG, 'utf8').split('\n').filter(Boolean)
      .flatMap((l) => { try { return [JSON.parse(l)]; } catch { return []; } })
  : [];

const raised = events.filter((e) => e.event === 'finding.raised');
const ruled = new Map(events.filter((e) => e.event === 'finding.ruled').map((e) => [e.ref, e]));

const scopeOf = (e) => (e.slice ? `Slice ${e.slice}` : `Phase ${e.phase ?? '0'}`);
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();

const VERDICT_MARK = {
  accepted: 'accepted', narrowed: 'narrowed', rejected: 'rejected',
  deferred: 'deferred', escalated: 'escalated',
};

/** Escape distance: loop steps between where a defect entered and where it was caught. */
const escapeDistance = (f) => {
  const introduced = Number(f.introduced_at_step);
  const found = Number(f.step);
  return Number.isFinite(introduced) && Number.isFinite(found) ? found - introduced : null;
};

const byScope = new Map();
for (const f of raised) {
  const k = scopeOf(f);
  if (!byScope.has(k)) byScope.set(k, []);
  byScope.get(k).push(f);
}

const counts = { BLOCKING: 0, MAJOR: 0, MINOR: 0 };
const verdicts = {};
const byRole = {};
let open = 0;
const distances = [];
for (const f of raised) {
  counts[f.severity] = (counts[f.severity] ?? 0) + 1;
  byRole[f.actor] = (byRole[f.actor] ?? 0) + 1;
  const r = ruled.get(f.ref);
  if (r) verdicts[r.verdict] = (verdicts[r.verdict] ?? 0) + 1;
  else open++;
  const d = escapeDistance(f);
  if (d !== null) distances.push(d);
}
const meanDistance = distances.length
  ? (distances.reduce((a, b) => a + b, 0) / distances.length).toFixed(2)
  : '—';

const lines = [
  '# Defect register',
  '',
  '**Generated by `npm run defects` — do not hand-edit.** Every row is derived from a',
  '`finding.raised` / `finding.ruled` pair in [`team-log/events.jsonl`](team-log/events.jsonl).',
  'A defect that is not in the log is not in this file, which is the point: the register cannot',
  'drift from the record, and `npm run log:audit` reconciles the record against git.',
  '',
  '> **What is here.** Anything crossing a role boundary — one role\'s finding about another\'s',
  '> work or about the design — including a role\'s finding against its own earlier work. A role\'s',
  '> in-flight self-correction is *not* a defect; recording those would make a careful role look',
  '> worse than a careless one.',
  '>',
  '> **Rejected findings stay, with their ruling.** A finding argued down on reasoning is evidence',
  '> the adjudication worked. The most valuable finding in slice 00a was one whose measurement was',
  '> right and whose proposed remedy would have broken the following slice — `narrowed` exists for',
  '> exactly that, because the finding and the remedy are separate verdicts.',
  '',
  '## Summary',
  '',
  '| | |',
  '|---|---|',
  `| Findings recorded | **${raised.length}** |`,
  `| Severity | ${counts.BLOCKING} blocking · ${counts.MAJOR} major · ${counts.MINOR} minor |`,
  `| Verdicts | ${Object.entries(verdicts).map(([k, v]) => `${v} ${k}`).join(' · ') || '—'} |`,
  `| Raised by | ${Object.entries(byRole).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(' · ') || '—'} |`,
  `| Awaiting a ruling | ${open === 0 ? 'none' : `**${open}**`} |`,
  `| Mean escape distance | ${meanDistance} step(s) |`,
  '',
  '*Escape distance is the number of loop steps between where a defect entered and where it was',
  'caught. Zero means it was caught in the step that produced it. It is the shift-left measure',
  '`team-log/process-criteria.md` names, and it is only computable because findings are logged',
  'rather than narrated.*',
  '',
];

for (const [scope, list] of byScope) {
  lines.push(`## ${scope}`, '');
  lines.push('| ref | sev | step | raised by | claim | verdict |');
  lines.push('|---|---|---|---|---|---|');
  for (const f of list) {
    const r = ruled.get(f.ref);
    const d = escapeDistance(f);
    const step = d === null ? `${f.step}` : `${f.step} *(+${d})*`;
    lines.push(
      `| **${esc(f.ref)}** | ${f.severity} | ${step} | ${esc(f.actor)} | ${esc(f.claim)} | ` +
      `${r ? VERDICT_MARK[r.verdict] ?? r.verdict : '**open**'} |`,
    );
  }
  lines.push('');
  const detailed = list.filter((f) => f.scenario);
  if (detailed.length) {
    lines.push('<details><summary>Failure scenarios and rulings</summary>', '');
    for (const f of detailed) {
      const r = ruled.get(f.ref);
      lines.push(`**${esc(f.ref)}** — ${esc(f.claim)}`, '');
      lines.push(`- *scenario:* ${esc(f.scenario)}`);
      if (f.file) lines.push(`- *file:* \`${esc(f.file)}\``);
      if (r) lines.push(`- *${r.verdict}* by ${esc(r.actor)} — ${esc(r.rationale)}`);
      lines.push('');
    }
    lines.push('</details>', '');
  }
}

lines.push(
  '---',
  '',
  '*A finding is recorded with `npm run log:append`; the orchestrator alone writes the log',
  '(`CLAUDE.md` §9). Regenerate with `npm run defects`; CI checks it with `npm run defects:check`.*',
  '',
);
const doc = lines.join('\n');

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== doc) {
    console.error('docs/DEFECTS.md is stale — run `npm run defects`.');
    process.exit(1);
  }
  console.log(`docs/DEFECTS.md is current (${raised.length} finding(s), ${open} open).`);
  process.exit(0);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, doc, 'utf8');
console.log(`docs/DEFECTS.md ← ${raised.length} finding(s), ${open} open, mean escape ${meanDistance}`);
