#!/usr/bin/env node
/**
 * THE TEST REPORT, DERIVED — never typed.
 *
 *   npm test -- --reporter=json --outputFile=test-results.json
 *   npm run mutation
 *   npm run test:report            # writes docs/TEST-REPORT.md
 *
 * ── Why this is a generator and not a document someone maintains ────────────────────────
 *
 * A hand-written test report is a set of numbers that were true once. This project has
 * caught that shape four times — `O-40`'s STATUS.md phase regression, `O-61`'s stale defect
 * register, `A-04-14`'s arc42 §13 sentence whose six hand-copied figures were all wrong
 * within two hours of being written, and `O-64`/`O-73`, where the gate read a number that
 * answered a different question. The lesson each time was the same: A DERIVED FILE
 * REGENERATED BY HAND IS STALE BY DEFAULT.
 *
 * So every figure here comes from an artifact:
 *
 *   tests            the Vitest JSON reporter's own output, merged across all three
 *                    projects by `tools/ci/run-tests.mjs`
 *   mutation         `reports/mutation/mutation.json`, Stryker's own report
 *   commit           `git rev-parse`, so a reader can tell what was measured
 *
 * ── The partial-report guard, inherited from O-73 ───────────────────────────────────────
 *
 * `npm run mutation` can be run file-scoped, and every run OVERWRITES the report. After the
 * slice 10 remediation a file-scoped run left a report containing ONE file, and collecting
 * from it produced a record saying no file was below threshold — true of the report and
 * false of the project. So this LABELS what it was given rather than presenting it as the
 * project's state: the file count is printed, and a report older than the last `src/` commit
 * carries a warning above the table. Labelled, not refused — a stale figure a reader can see
 * is stale beats no figure, and refusing would break the tool exactly when it is most wanted.
 */

import { readFileSync, existsSync, writeFileSync, statSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';

const RESULTS = process.env.RESULTS ?? 'test-results.json';
const MUTATION = 'reports/mutation/mutation.json';
const OUT = 'docs/TEST-REPORT.md';

/**
 * What each suite is FOR. Counts alone do not say why 15 concurrency tests matter more than
 * 517 unit tests, and a report that cannot say that is a table rather than a report.
 */
const PURPOSE = {
  acceptance: 'Drives the built artifact over HTTP. Defines *done* for a slice; the test-engineer writes these before any implementation exists.',
  contract: 'Asserts the emitted OpenAPI document against the service — every error declared as `application/problem+json` on the operations that can produce it, by equality.',
  integration: 'Database invariants through the real schema: the exclusion constraints, the audit trigger, the telemetry spans.',
  concurrency: 'The system\'s central claim. Racers from a hard barrier against one slot; the DATABASE decides, and exactly one row survives.',
  property: 'Generated inputs against an oracle — the availability query is checked against what the constraint actually permits, not against a fixture.',
  performance: 'QS-14\'s budget, in its own Vitest project with its own container so it is never measured beside the twenty-racer suite.',
  architecture: 'Layering and containment, enforced by `dependency-cruiser` plus negative controls that plant a violation and expect rejection.',
  unit: 'The implementer\'s design tool: fast, no database, and the only suite Stryker measures.',
};

const sh = (cmd, args) => { try { return execFileSync(cmd, args, { encoding: 'utf8' }).trim(); } catch { return 'unknown'; } };

function suites(results) {
  const by = new Map();
  for (const f of results.testResults ?? []) {
    const dir = f.name.replace(/.*\/tests\//, '').split('/')[0];
    const v = by.get(dir) ?? { files: 0, passed: 0, failed: 0, ms: 0 };
    v.files++;
    for (const a of f.assertionResults ?? []) (a.status === 'passed' ? v.passed++ : v.failed++);
    v.ms += (f.endTime ?? 0) - (f.startTime ?? 0);
    by.set(dir, v);
  }
  return [...by.entries()].sort((a, b) => b[1].passed - a[1].passed);
}

/**
 * STALENESS IS REPORTED, NOT ASSUMED AWAY — O-73's lesson, one level up.
 *
 * A report on disk may be THIS run's or a PREVIOUS one's — observed both ways: the file was
 * absent during one run and present two minutes into another, so its existence says nothing
 * about whether a run is in flight. What it cannot be is newer than the run that wrote it, so
 * its mtime against the last `src/` commit is the honest test. Generating from a report older
 * than the code produces a document whose numbers were true of source that no longer exists —
 * precisely how `O-73` happened: a figure true of its input and false of the project.
 *
 * It is labelled rather than refused, because a stale figure a reader can see is stale is
 * worth more than no figure at all — and because refusing would make this tool unusable in
 * exactly the case it is most wanted, immediately after a change.
 */
function mutationAgeAgainstSource() {
  try {
    const reportAt = statSync(MUTATION).mtimeMs;
    const srcAt = Date.parse(sh('git', ['log', '-1', '--format=%cI', '--', 'src/']));
    return Number.isNaN(srcAt) ? null : { stale: reportAt < srcAt, reportAt, srcAt };
  } catch { return null; }
}

function mutation() {
  if (!existsSync(MUTATION)) return null;
  const r = JSON.parse(readFileSync(MUTATION, 'utf8'));
  const files = [];
  let killed = 0, total = 0;
  for (const [k, f] of Object.entries(r.files ?? {})) {
    const counted = (f.mutants ?? []).filter((m) => ['Killed', 'Timeout', 'Survived'].includes(m.status));
    if (!counted.length) continue;
    const k2 = counted.filter((m) => m.status !== 'Survived').length;
    files.push({ file: k.replace(`${process.cwd()}/`, ''), score: (k2 / counted.length) * 100, killed: k2, survived: counted.length - k2 });
    killed += k2; total += counted.length;
  }
  files.sort((a, b) => a.score - b.score);
  return { files, score: total ? (killed / total) * 100 : 0, killed, total, age: mutationAgeAgainstSource() };
}

const results = existsSync(RESULTS) ? JSON.parse(readFileSync(RESULTS, 'utf8')) : null;
if (!results) {
  console.error(`no ${RESULTS}. Run: npm test -- --reporter=json --outputFile=${RESULTS}`);
  process.exit(2);
}
const mut = mutation();
const rows = suites(results);
const files = rows.reduce((n, [, v]) => n + v.files, 0);
const passed = rows.reduce((n, [, v]) => n + v.passed, 0);
const failed = rows.reduce((n, [, v]) => n + v.failed, 0);

const out = [];
out.push('# Test report');
out.push('');
out.push(`> **Generated** by \`npm run test:report\` from \`${RESULTS}\` and \`${MUTATION}\`.`);
out.push('> Every figure below comes from a tool\'s own output. Do not edit this file — regenerate it.');
out.push(`> Commit \`${sh('git', ['rev-parse', '--short', 'HEAD'])}\` · ${new Date().toISOString()}`);
out.push('');
out.push(`**${passed} tests across ${files} files, ${failed} failing.**`);
out.push('');
out.push('| Suite | Files | Tests | Failed | Time |');
out.push('|---|---:|---:|---:|---:|');
for (const [d, v] of rows) out.push(`| \`tests/${d}/\` | ${v.files} | ${v.passed} | ${v.failed} | ${(v.ms / 1000).toFixed(1)}s |`);
out.push(`| **Total** | **${files}** | **${passed}** | **${failed}** | |`);
out.push('');
out.push('## What each suite is for');
out.push('');
for (const [d] of rows) if (PURPOSE[d]) out.push(`**\`tests/${d}/\`** — ${PURPOSE[d]}\n`);

out.push('## Mutation');
out.push('');
if (!mut) {
  out.push('_No mutation report. Run `npm run mutation`._');
} else {
  const mutated = mut.files.length;
  out.push(`**${mut.score.toFixed(2)}% overall** — ${mut.killed} killed of ${mut.total} counted, across ${mutated} files.`);
  out.push('');
  if (mut.age?.stale) {
    out.push('> ⚠ **This mutation report predates the last change under `src/`.** It describes code that');
    out.push('> has since moved. Re-run `npm run mutation` before trusting the figures below.');
    out.push('');
  }
  out.push('Stryker\'s config mutates `src/**` and runs `tests/unit/**` only, so a mutant killed');
  out.push('outside-in is invisible here. That is recorded as `F-06-2`, and it means these are a');
  out.push('**floor** rather than the whole truth.');
  out.push('');
  out.push('§10\'s threshold is **0.75, per changed file** — not the aggregate. Reading the aggregate');
  out.push('against it was `O-64`: at slice 08 the changed set scored 85.71 while one file sat at 71.43.');
  out.push('');
  out.push('| File | Score | Killed | Survived |');
  out.push('|---|---:|---:|---:|');
  for (const f of mut.files) out.push(`| \`${f.file}\` | ${f.score < 75 ? `**${f.score.toFixed(2)}**` : f.score.toFixed(2)} | ${f.killed} | ${f.survived} |`);
  const low = mut.files.filter((f) => f.score < 75);
  out.push('');
  out.push(low.length
    ? `**${low.length} file(s) below 0.75**: ${low.map((f) => `\`${f.file}\``).join(', ')}.`
    : '**Every mutated file is at or above 0.75.**');
}
out.push('');
writeFileSync(OUT, `${out.join('\n')}\n`, 'utf8');
console.log(`${OUT} ← ${passed} tests, ${files} files${mut ? `, mutation ${mut.score.toFixed(2)}%` : ', no mutation report'}`);
